---
- name: Install Grafana
  hosts: hosts
  become: yes
  
  tasks:
  - name: download rpm key
    ansible.builtin.rpm_key:
      key: https://packages.grafana.com/gpg.key
      state: present
  - name: Add grafana repo to sources.list
    ansible.builtin.yum_repository:
      baseurl: rpm https://packages.grafana.com/oss/rpm stable main
      description: Grafana Repo
      name: grafana
      state: present
  # - name: Update cache and install Grafana
  # - name: Ensure Grafana is started and enabled
