---
- name: Uninstall Grafana
  hosts: hosts
  become: yes
  
  tasks:
  - name: Remove rpm key
    ansible.builtin.rpm_key:
      key: https://packages.grafana.com/gpg.key
      state: absent
  - name: Remove grafana repo from sources.list
    ansible.builtin.yum_repository:
      baseurl: https://packages.grafana.com/oss/rpm
      description: Grafana Repo
      name: grafana
      state: absent
  - name: Uninstall Grafana
    ansible.builtin.yum:
      name: grafana
      state: absent
