---
- name: Bootstrap Main Node
  hosts: main
  become: yes
  
  tasks:
  - name: download rpm key
    ansible.builtin.rpm_key:
      key: https://packages.grafana.com/gpg.key
      state: present
  - name: Add grafana repo to sources.list
    ansible.builtin.yum_repository:
      baseurl: https://packages.grafana.com/oss/rpm
      description: Grafana Repo
      name: grafana
      state: present
  - name: Update cache and install Grafana
    ansible.builtin.yum:
      name: grafana
      update_cache: yes
  - name: Ensure Grafana is started and enabled
    systemd:
      name: grafana-server
      state: started
      enabled: yes
  - name: Download Prometheus
  - name: Extract Prometheus Resources
  - name: Create Prometheus Group
  - name: Create Prometheus User
  - name: Create Prometheus Directories
  - name: Set Permissions
  - name: Copy Files
  - name: Second Copy of Files
  - name: Create Config Files
  - name: Create Systemd Files
  - name: Ensure Prometheus is Started
    
    
