---
- name: Bootstrap Main Node
  hosts: main
  become: yes
  
  tasks:
  - name: download rpm key
    ansible.builtin.rpm_key:
      key: https://packages.grafana.com/gpg.key
      state: present
  - name: Add grafana repo to sources.list
    ansible.builtin.yum_repository:
      baseurl: https://packages.grafana.com/oss/rpm
      description: Grafana Repo
      name: grafana
      state: present
  - name: Update cache and install Grafana
    ansible.builtin.yum:
      name: grafana
      update_cache: yes
  - name: Ensure Grafana is started and enabled
    systemd:
      name: grafana-server
      state: started
      enabled: yes
  - name: Download Prometheus
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.41.0/prometheus-2.41.0.linux-amd64.tar.gz
      dest: /home/ec2-user
  - name: Extract Prometheus Resources
    ansible.builtin.unarchive:
      src: /home/ec2-user/prometheus-2.41.0.linux-amd64.tar.gz
      dest: /home/ec2-user
      remote_src: yes
  - name: Create Prometheus Group
    ansible.builtin.group:
      name: prometheus
      state: present
  - name: Create Prometheus User
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      shell: /sbin/nologin
  - name: Create Prometheus Directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      owner: prometheus
      group: prometheus
      mode: '0755'
    loop:
      - /etc/prometheus
      - /etc/prometheus/rules
      - /etc/prometheus/rules.d
      - /etc/prometheus/files_sd
      - var/lib/prometheus
  - name: Copy Files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /usr/local/bin
      remote_src: yes
      owner: prometheus
      group: prometheus
    loop:
      - /home/ec2-user/prometheus-2.41.0.linux-amd64/prometheus
      - /home/ec2-user/prometheus-2.41.0.linux-amd64/promtool
  - name: Second Copy of Files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/prometheus
      remote_src: yes
    loop:
      - /home/ec2-user/prometheus-2.41.0.linux-amd64/consoles
      - /home/ec2-user/prometheus-2.41.0.linux-amd64/console_libraries
      
  # - name: Create Config Files
  # - name: Create Systemd Files
  # - name: Ensure Prometheus is Started
    
    
